### PR TITLE
Added cluster metric of total scanned rows and users

### PR DESCRIPTION
**Pull request by sbernauer**
Change is backward-compatible and will pick up existing queries.
Screenshot after the change
image

### CODE REVIEW

**Comment by Guy-Mast** [comment]
@sbernauer thanks for your contribution! can you please squash the commits so will have just one commit in this PR?

**Comment by sbernauer** [comment]
Hi @Guy-Mast of course, did so

**Comment by Guy-Mast** [comment]
Hi @sbernauer, IMO breaking this sentence into two sentences will make it clearer to readers. We can do something like: 
The Workload Analyzer ran over a period of D days and analyzed Q queries that were executed by U users. During this period R rows and T TB of data were scanned.

WDYT?

**Comment by sbernauer** [comment]
image
Is this fine?

**Pull request merged**
